version: "3.8"

services:
  grafana:
    image: grafana/grafana:11.4.0
    container_name: aws-tagging-grafana
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      # Provisioning automatique (datasource + dashboards)
      - ../grafana/provisioning:/etc/grafana/provisioning
      # Dashboards JSON
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      # Persistence des donnees Grafana
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
